### ISSUE TITLE
 Instructions on training the model 

### ISSUE THREAD

**Issue by AloshkaD** [SummitKwan/transparent_latent_gan#12]
Thanks for sharing the repo. I wonder when will you be able to share the training part with instructions.

Thanks!

**Comment by SummitKwan** [comment]
> Thanks for sharing the repo. I wonder when will you be able to share the training part with instructions.
> 
> Thanks!

Thank you for your interest!  I am trying to finish that part on Wednesday.  By the way, does the testing part runs well on your machine?

**Comment by pixieDoug** [comment]
@SummitKwan It runs well on my machine.  i7 32gig, 1080ti, Win10

**Comment by leraShtotland** [comment]
I also wonder when will you be able to share the instructions of the training part? 

Thank you!!!

**Comment by pixieDoug** [comment]
Are the training instructions up?  I don't see them in the readme.

Thanks!

**Comment by voa18105** [comment]
Waiting for the training instructions ^_^ +1

**Comment by basilzeno** [comment]
Waiting for the training instructions )) +1

**Comment by AloshkaD** [comment]
+1

**Comment by anna-mo** [comment]
waiting for the training instruction, too. And also keep focus on if there will  have  a  instructions for using  random local pics with  the features model.

**Comment by seizeMx** [comment]
Thanks SummitKwan! Great project, and I am wondering the instructions too :)
