### ISSUE TITLE
Should Linear Classifier  be replace by a multilabel classifier?

### ISSUE THREAD

**Issue by shartoo** [SummitKwan/transparent_latent_gan#25]
As shown in demo ,many attribution of a generated image can be adjusted. When preparing my own dataset,such as Celeba-HQ which every sample has 40 attributions(`Gray_Hair`,`Heavy_Makeup	`,`High_Cheekbones`,`Male`...).This is obviously a multilabel classify problem, likewise with current repo ,simple LinearRegression seems work at th begining but fails as dataset size increase(from 4000 to 8000 image samples). Some of my result comes from LinearRegression model trained on 4000 image samples of Celeba-HQ

+ **original image**

![ori_00036](https://user-images.githubusercontent.com/5716282/63080405-909f1600-bf73-11e9-95d2-39ef531b1096.jpg)

+ **with eyeglass**

![Eyeglasses_00036_old](https://user-images.githubusercontent.com/5716282/63080425-9eed3200-bf73-11e9-8296-06e0855e8dda.jpg)

+ **with beard**

![No_Beard_00036_old](https://user-images.githubusercontent.com/5716282/63080448-ac0a2100-bf73-11e9-9ca3-3a13c79e40f2.jpg)

+ **smiling**

![Smiling_00036](https://user-images.githubusercontent.com/5716282/63080584-07d4aa00-bf74-11e9-9f92-acb93e0ba92e.jpg)

**I want to change some other attribution but all failed**

**Comment by shartoo** [comment]
The above image are generated with the help of `feature_axis.py` and  `script_label_regression.py` without any change combined with StyleGAN with a dataset of 4000 samples.As image samples  grown to 8000,a newer model was trained ,but i could't change any attribution any more . I thought this must be caused by sth with data itself like class imblance and so on , so tried a multilabel classify model  accoring to `find_feature_axis` method in `feature_axis.py`

```
def find_feature_axis_multilabel(z, y):
    """
        a  multilabel classify model
    :param z: vectors in the latent space, shape=(num_samples, num_latent_vector_dimension)
    :param y: feature vectors, shape=(num_samples, num_features)
    :return: feature vectors, shape = (num_latent_vector_dimension, num_features)
    """
    mb = MultiLabelBinarizer()
    y = mb.fit_transform(y)
    clf = OneVsRestClassifier(LogisticRegression(), n_jobs=-1)
    clf.fit(z, y)
    # training set result
    y_predicted = clf.predict(z)
    # report
    print(metrics.classification_report(y,y_predicted))
    accuracy = np.mean(y_predicted == y)
    print("model accuracy ",accuracy)
    return clf.coef_.transpose()
```

and error occur 

```
File "script_label_regression.py", line 99, in <module>
    train_direction_model(z_arr,y_arr,path_celeba_att,path_feature_direction)
  File "script_label_regression.py", line 54, in train_direction_model
    multilabel = feature_axis.find_feature_axis_multilabel(z, y)
  File "/home/xiatao/work/swap_face/stylegan-encoder/feature_axis.py", line 57, in find_feature_axis_multilabel
    return clf.coef_.transpose()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py", line 389, in coef_
    "Base estimator doesn't have a coef_ attribute.")
AttributeError: Base estimator doesn't have a coef_ attribute.
```
I can't return the coef of this multilabel classify model.

**Comment by shartoo** [comment]
Effect of trump

**original trump**

![ori_trump](https://user-images.githubusercontent.com/5716282/63082608-3d2fc680-bf79-11e9-894e-90a091e1075d.jpg)

**Smiling**

![Smiling_trump](https://user-images.githubusercontent.com/5716282/63082585-2b4e2380-bf79-11e9-8094-07e6ce293eee.jpg)

**Eyeglasses**

![Eyeglasses_trump](https://user-images.githubusercontent.com/5716282/63082600-3608b880-bf79-11e9-9677-537cb96c3221.jpg)

**Bushy Eyebrows**

![Bushy_Eyebrows_trump](https://user-images.githubusercontent.com/5716282/63083171-a532dc80-bf7a-11e9-91ff-22af6a437c99.jpg)

**Comment by SummitKwan** [comment]
Hi, first, thanks for testing the code and try with different dataset.  It seems to me that the OneVsAll classier is not a good strategy since for every label, there are only two classes, i.e., every labels simply requires a binary classifier.  The classification of any label can be independent.   I would suggest try to see if class imbalance is bad or not in this case.

**Comment by shartoo** [comment]
I tried a SVM model with `class_weight =balanced`  and removed an attribution of data annotation named `Blurry` whose values are always be `1` but result remains the same,i'll try some other solution later ,thank you!

**Comment by shartoo** [comment]
SVM model works now,i can adjust most attribution on faces.

```
clf = OneVsRestClassifier(SVC(kernel='linear',class_weight="balanced"), n_jobs=-1)
clf.fit(z, y)
```

**Comment by shartoo** [comment]
Result
![1](https://user-images.githubusercontent.com/5716282/63312901-74b1c080-c335-11e9-85ae-5449c5642324.png)
![2](https://user-images.githubusercontent.com/5716282/63312902-74b1c080-c335-11e9-8626-ab7249a61442.png)
![3](https://user-images.githubusercontent.com/5716282/63312903-74b1c080-c335-11e9-8878-5f5fc6e5ad7b.png)
![4](https://user-images.githubusercontent.com/5716282/63312904-754a5700-c335-11e9-970e-1edcd380d0e8.png)
![5-1](https://user-images.githubusercontent.com/5716282/63312905-75e2ed80-c335-11e9-99cb-110a7241c571.png)
![6](https://user-images.githubusercontent.com/5716282/63312906-75e2ed80-c335-11e9-9ca1-8257459ae79d.png)
![7](https://user-images.githubusercontent.com/5716282/63312908-77141a80-c335-11e9-81e1-8b2f3424a669.png)
![8](https://user-images.githubusercontent.com/5716282/63312909-77141a80-c335-11e9-9d89-bbfe462173db.png)
![9](https://user-images.githubusercontent.com/5716282/63312915-78ddde00-c335-11e9-8e26-04bbdd5675fc.png)
![10](https://user-images.githubusercontent.com/5716282/63312917-79767480-c335-11e9-8a5f-5fab2acb3e7a.png)
![11](https://user-images.githubusercontent.com/5716282/63312922-7aa7a180-c335-11e9-8980-2b9b50359b35.png)
![12](https://user-images.githubusercontent.com/5716282/63312928-7bd8ce80-c335-11e9-879a-41937024b9a9.png)
![13](https://user-images.githubusercontent.com/5716282/63312930-7d09fb80-c335-11e9-8e94-9055fcd25e3e.png)
![14](https://user-images.githubusercontent.com/5716282/63312937-7e3b2880-c335-11e9-8b2f-44dfa71714ce.png)
![15](https://user-images.githubusercontent.com/5716282/63312939-7f6c5580-c335-11e9-99fa-5166575694ff.png)
![16](https://user-images.githubusercontent.com/5716282/63312940-7f6c5580-c335-11e9-865a-aa31b37c6035.png)
![17](https://user-images.githubusercontent.com/5716282/63312945-809d8280-c335-11e9-926e-a613f5484ebe.png)
![18](https://user-images.githubusercontent.com/5716282/63312946-81361900-c335-11e9-9636-2af7beb7bbf1.png)
![19](https://user-images.githubusercontent.com/5716282/63312948-82ffdc80-c335-11e9-8fbd-4681e3d7f478.png)
![20](https://user-images.githubusercontent.com/5716282/63312950-82ffdc80-c335-11e9-80aa-0fcedb8f2567.png)
![21](https://user-images.githubusercontent.com/5716282/63312954-84c9a000-c335-11e9-9298-4ae1b225cd3d.png)
![22](https://user-images.githubusercontent.com/5716282/63312956-84c9a000-c335-11e9-9754-386c7edc92e4.png)
![23png](https://user-images.githubusercontent.com/5716282/63312958-85facd00-c335-11e9-90e6-257677af15d0.png)

**Comment by SummitKwan** [comment]
Looks super encouraging!  Thanks for sharing
